server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        # - 是yml语法，代表数组的意思
        - id: payment_route1 # 路由ID，没有固定规则，需要保证唯一
          #uri: http://localhost:8001 # 路由到哪个地址，实际提供微服务的地址
          uri: lb://CLOUD-PAYMENT-SERVICE  # 使用微服务名称查找路由地址，lb是用于识别负载均衡的前缀，不能修改
          predicates:
            - Path=/payment/get/** # 路径匹配断言
            #- After=2020-12-24T07:20:33.393+08:00[Asia/Shanghai]  # 在此时间后可访问
            #- Before=2020-12-25T07:20:33.393+08:00[Asia/Shanghai] # 在此时间前可访问
            #- Between=2020-12-24T07:20:33.393+08:00[Asia/Shanghai], 2020-12-25T08:10:33.393+08:00[Asia/Shanghai] #在此时间范围内可访问
            #- Cookie=username,yaojianhua #带cookies验证的；curl http://localhost:9527/payment/get/13 --cookie "username=yaojianhua"
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为整数的正则表达式; curl http://localhost:9527/payment/get/13 -H "X-Request-Id:123"
            #- Host=**.baidu.com,**.atguigu.com #指定域名的可方法地址 ；curl http://localhost:9527/payment/get/13 -H "Host:www.atguigu.com"
            #- Method=GET,POST


        - id: payment_route2 # 路由ID，没有固定规则，需要保证唯一
          #uri: http://localhost:8001 # 路由到哪个地址，实际提供微服务的地址
          uri: lb://CLOUD-PAYMENT-SERVICE # 使用微服务名称查找路由地址，lb是用于识别负载均衡的前缀，不能修改
          predicates:
            - Path=/payment/loadbalance # 路径匹配断言
            - After=2020-12-24T07:20:33.393+08:00[Asia/Shanghai]
          #filters:
          #  - AddRequestHeader=X-Request-red, blue



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true # true：将自己注册进Eureka
    fetch-registry: true # true：需要去注册中心获取其他服务地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/